pipeline:
  name: javaBookStore
  identifier: javaBookStore
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: GitHub
        repoName: Bookstore
        build: <+input>
  stages:
    - stage:
        name: build
        identifier: build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: |
                      java --version
                      mvn -v 
              - step:
                  type: Run
                  name: Run_2
                  identifier: Run_2
                  spec:
                    shell: Sh
                    command: |
                      npm install snyk -g
                      snyk auth 02c3f931-9df9-4358-b837-581e75ee6ce4
                      snyk monitor
                      snyk ignore --path<src/main/java/servlets/BuyBooksServlet.java>
                      snyk code test 
