pipeline:
  name: javaBookStore
  identifier: javaBookStore
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: GitHub
        repoName: Bookstore
        build: <+input>
  stages:
    - stage:
        name: Testing
        identifier: Testing
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: SNYK
                  identifier: SNYK
                  spec:
                    shell: Sh
                    command: |
                      npm install snyk -g
                      snyk auth 02c3f931-9df9-4358-b837-581e75ee6ce4
                      snyk monitor
                      snyk test --severity-threshold=critical
          caching:
            enabled: false
            paths: []
    - stage:
        name: war file
        identifier: war_file
        description: ""
        type: CI
        spec:
          cloneCodebase: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: |-
                      mvn --version
                      mvn clean install
